#!/usr/bin/bash

userpass=$1
fileordir=$2
rdir=https://dav.jianguoyun.com/dav/jianguo/$3
timestr=$(date -Iseconds)
tmpdir=/tmp/jianguo$timestr
mkdir $tmpdir
curl -u $1 --create-dirs $rdir
if [-f "$fileordir" ]; then
curl -u $1 -T $fileordir $rdir
else if [-d "$fileordir" ]; then
cp $files/* $tmpdir/*
for s in $tmpdir/*
do
 $0 $1 $s $3/$(basename $fileordir)
done
fi
