#!/usr/bin/bash

userpass=$1
fileordir=$2
rdir="https://dav.jianguoyun.com/dav/jianguo/"
timestr=$(date -Iseconds)
tmpdir=/tmp/jianguo$timestr
mkdir $tmpdir
curl -u $1 --create-dirs $rdir
if [-f "$fileordir" ]; then
curl -u $1 -T $fileordir $rdir
else if [-d "$fileordir" ]; then
cp $files/* $tmpdir/*
for s in $tmpdir/*
do
 if [-f "$fileordir" ]; then
    curl $1 -T $s $rdir
 fi
done
else 
 echo `file or dir dose not exist"
fi
